package model

var (
	ProtectedTerms = []string{
		"Uyghur (Arabic transcription)",
		"Ancient Greek (transliterated)",
		"Serbian (Cyrillic script)",
		"Crayola Cutter (TM)",
		"Acryloid (TM)",
		"Ageless (TM)",
		"Aquazol (TM)",
		"Arigal C (TM)",
		"Super-VHS (TM)",
		"VistaVision (TM)",
		"Kevlar (TM)",
		"Scleroscopes (TM)",
		"Hammond organs (TM)",
		"Astroturf (TM)",
		"Cibachrome (TM)",
		"Ektachrome (TM)",
		"Bake-Offs (TM)",
		"Eastman Wash-off Relief (TM)",
		"Mixografia (R)",
		"Carborundum (TM)",
		"Hydrocal (TM)",
		"Vinylite (TM)",
		"Bakelite (TM)",
		"Conté crayon (TM)",
		"Cor-Ten steel (TM)",
		"Inconel (TM)",
		"Zonolite concrete (TM)",
		"Pyrex (TM)",
		"Automats (TM)",
		"construction T&amp;E (blank sub-class)",
		"Greek (transliterated)",
		"Uyghur (Cyrillic transcription)",
		"Serbian (Latin script)",
		"Photostat Machines (TM)",
		"Diasec (TM)",
		"Agfacolor (TM)",
		"Thermo Lignum (TM)",
		"Digital Betacam (TM)",
		"Erector Sets (TM)",
		"Klieglights (TM)",
		"Kodachrome (TM)",
		"Duratrans (TM)",
		"Betacam (TM)",
		"Formica (TM)",
		"Perlon (R)",
		"Invar (TM)",
		"Monel (TM)",
		"Uyghur (Latin transcription)",
		"Photostats (TM)",
		"Araldite (TM)",
		"Vikane (R)",
		"Paraloid B-67 (TM)",
		"Piezo (R) prints",
		"Kodacolor (TM)",
		"Pictrography (TM)",
		"IMAX (TM)",
		"Arches paper (R)",
		"Paraloid B-72 (TM)",
		"Geodimeters (TM)",
		"Opalon (TM)",
		"Micarta (TM)",
		"Dacron (TM)",
		"Plumbicons (TM)",
		"Papersave Process (TM)",
		"Arjomari paper (R)",
		"Paraloid (TM)",
		"Thermoses (TM)",
		"Plexisol P550 (TM)",
		"Resistograph (TM)",
		"Art Sorb (TM)",
		"Plastic Wood (TM)",
		"Polyfilla (TM)",
		"Beaverboard (TM)",
		"Favrile glass (TM)",
		"Profilometers (TM)",
		"Piezography (R)",
		"Spackle (TM)",
		"Lally columns (TM)",
		"Hoberman spheres (TM)",
		"Synperonic (TM)",
		"BEVA 371 (TM)",
		"View-Masters (TM)",
		"Carbopol (TM)",
		"Ziploc (TM)",
		"Carrara structural glass (TM)",
		"Ross board (TM)",
		"Celotex (TM)",
		"Naugahyde (TM)",
		"Corrosion Intercept (TM)",
		"CSC Book Saver (TM)",
		"window &amp; door coverings (blank sub-class)",
		"Day-Glo (TM)",
		"Delrin (TM)",
		"Devcon (TM)",
		"Dralon (R)",
		"Dulux (TM)",
		"floor coverings (blank sub-class)",
		"Fome-Cor (R)",
		"Fujichrome (TM)",
		"Gore-Tex (TM)",
		"Hexalite (TM)",
		"Hexlite (TM)",
		"Incralac (TM)",
		"JunFunori (TM)",
		"Kauramin (TM)",
		"Laponite (TM)",
		"Lucite (TM)",
		"Masonite (TM)",
		"Melinex (TM)",
		"Mowilith (TM)",
		"Mylar (TM)",
		"Parafilm M (TM)",
		"Paraprint OL 60 (TM)",
		"Akkadian (transliterated)",
		"Parylene (TM)",
		"Perspex (TM)",
		"Plexiglas (TM)",
		"Velcro (TM)",
		"Poligen (TM)",
		"Regalrez (TM)",
		"Regnal (TM)",
		"Rhoplex resin (TM)",
		"Sokrat (TM)",
		"Stabiltex (TM)",
		"Styrofoam (TM)",
		"Super Glue (TM)",
		"Teflon (TM)",
		"Tupperware (TM)",
		"Tylose (TM)",
		"Tyvek (TM)",
		"Vaseline (TM)",
		"Vitrolite (TM)",
		"Wite-Out (TM)",
		"Zamak (TM)",
		"Amharic (transliterated)",
		"Ancient Hebrew (transliterated)",
		"Ancient Macedonian (transliterated)",
		"Arabic (transliterated)",
		"Aramaic (transliterated)",
		"Armenian (transliterated)",
		"Assamese (transliterated)",
		"mining &amp; mineral harvesting T&amp;E (blank sub-class)",
		"sports equipment (blank sub-class)",
		"Belorussian (transliterated)",
		"Bengali (transliterated)",
		"Bulgarian (transliterated)",
		"Burmese (transliterated)",
		"Chinese (simplified)",
		"Chinese (traditional)",
		"Chinese (transliterated)",
		"Chinese (transliterated Hanyu Pinyin)",
		"Chinese (transliterated Pinyin)",
		"Chinese (transliterated Pinyin without tones)",
		"Chinese (transliterated Tongyong Pinyin)",
		"Chinese (transliterated Wade-Giles)",
		"Chinese (Zhuyin transcription)",
		"Dari (transliterated)",
		"Dzongkha (transliterated)",
		"Georgian (transliterated)",
		"Gujarati (transliterated)",
		"Hebrew (transliterated)",
		"Hindi (transliterated)",
		"Japanese (transliterated)",
		"Kannada (transliterated)",
		"Kazakh (transliterated)",
		"Khmer (transliterated)",
		"Kongo (Congo)",
		"Konkani (transliterated)",
		"Korean (transliterated)",
		"Kyrgyz (transliterated)",
		"Lao (transliterated)",
		"Lappish (Finno-Ugric)",
		"Magyar (Hungarian)",
		"Malayalam (transliterated)",
		"Maldivian (transliterated)",
		"Marathi (transliterated)",
		"Mongolian (transliterated)",
		"Nepali (transliterated)",
		"Norwegian (Bokmål)",
		"Norwegian," +
			"New (Nynorsk)",
		"Pali (transliterated)",
		"Pashto (transliterated)",
		"Persian-Farsi (transliterated)",
		"Pohnpeian (Ponapean)",
		"Romansch (Rhaeto-Roman)",
		"Russian (transliterated)",
		"Sanskrit (transliterated)",
		"Sinhala (transliterated)",
		"Sumerian (transliterated)",
		"Swati (Swazi)",
		"Tajik (transliterated)",
		"Tamajeq (Tamasheq)",
		"Tamil (transliterated)",
		"Thai (transliterated)",
		"Tibetan (transliterated)",
		"Tigrinya (transliterated)",
		"Tok Pisin (Neomelanesian)",
		"Tongan (Tongalese)",
		"Tulu (transliterated)",
		"Turkish (transliterated)",
		"Ukrainian (transliterated)",
		"Urdu (transliterated)",
		"Yami (Batanic)",
	}
)
